### ISSUE TITLE
Exception swallowing

### ISSUE THREAD

**Issue by hryo** [sendgrid/csharp-http-client#6] opened 2016-06-20 23:06 UTC
`catch (Exception ex)
                {
                    HttpResponseMessage response = new HttpResponseMessage();
                    string message;
                    message = (ex is HttpRequestException) ? ".NET HttpRequestException" : ".NET Exception";
                    message = message + ", raw message: \n\n";
                    response.Content = new StringContent(message + ex.Message);
                    return new Response(response.StatusCode, response.Content, response.Headers);
                }`

As you can see response always initializes with StatusCode.Ok. 
It's not possible with such implementation to track when client throws something.

**Comment by thinkingserious** [comment] 2016-06-20 23:10
Hi @hyro,

I see, we are only returning the error message and we have failed to set the status code. I'm going to classify this as a bug.

Thanks for taking the time to let us know!

**Comment by thinkingserious** [comment] 2016-06-28 17:55
Hello @hryo,

I am now trying to reproduce the issue and I'm not sure I understand what you are requesting.

For example, if I try and make an API call with a non-existent endpoint, the return is:

```
NotFound
{"errors":[{"field":null,"message":"resource not found"}]}
Connection: keep-alive
Date: Tue, 28 Jun 2016 17:53:47 GMT
```

I'm not sure where you are seeing that StatusCode.OK is being always initialized.

**Comment by davidhagg** [comment] 2017-01-09 12:40
Looked into this and the status code is returned correctly if there is a valid response, like 404, 401 etc. However if there is network issues an exception will be thrown and the exception handling will cause the status code to always be 200. It is also hiding the real exception so the consumer of the lib cannot see the underlying cause.

I've filed a PR with a potential fix
#20

**Comment by Tarball** [comment] 2017-01-19 23:12
Could this code simply rethrow the exception and allow the calling code to decide how to handle it?
I'm trying to implement a retry strategy for transient errors when calling the SendGrid API. These include HTTP 5xx status codes, but also network errors such as timeouts and connection resets that should result in an exception being thrown by HttpClient SendAsync().
I would like to be able to catch these and retry the operation. Currently, an exception just causes the response object to have StatusCode 200 which looks like a success. The only way to tell an exception occurred is to parse the response contents string.

**Comment by thinkingserious** [comment] 2017-05-01 00:19
Hello @hryo, @Tarball,

This issue is now fixed: https://github.com/sendgrid/sendgrid-csharp/pull/434

Thanks!

**Closed as completed by thinkingserious** 2017-05-01 00:19 UTC
Labels: type: bug, status: help wanted
